return non-zero exit code if test setup fails
polyfy/polylith pull request #232
Opened 2022-06-06 05:35 UTC by Devgrapher

Fix #229 

This PR is just to give a hint to fix the issue I reported.
It seems to fix the issue but I'm not sure if this is the right way to fix it since I'm not used to the codebase.

2022-06-06 06:41 UTC, imrekoszo commented on components/test-runner-orchestrator/src/polylith/clj/core/test_runner_orchestrator/core.clj
> +            setup-failed? #(not (deref setup!*))
With this change, setup will run in line 108 even when there are no test runners that find any tests (see the implementation of `run-tests-for-project-with-test-runner`). I would probably suggest making line 67 an `if` and throwing on its else branch. What do you think? Is there something I'm missing?

2022-06-06 08:00 UTC, tengstrand requested changes
Also update :
https://github.com/polyfy/polylith/blob/7c6c94ada0a680476e74b64e903cd4b57783bd26/components/version/src/polylith/clj/core/version/interface.clj#L7
To `alpha-issue229-01` and the date:
https://github.com/polyfy/polylith/blob/7c6c94ada0a680476e74b64e903cd4b57783bd26/components/version/src/polylith/clj/core/version/interface.clj#L10

This is a "service" for people who execute the `poly` tool via a hash, so that the version can be checked by executing `poly version`.

2022-06-11 05:20 UTC, Devgrapher commented on components/test-runner-orchestrator/src/polylith/clj/core/test_runner_orchestrator/core.clj
> +            setup-failed? #(not (deref setup!*))
Yes, you're totally right. I'll move the `if`. Thanks!

2022-06-11 10:15 UTC, imrekoszo approved these changes, later dismissed

2022-06-17 05:18 UTC, tengstrand commented
Looks like we can merge this now @imrekoszo?

2022-06-17 06:54 UTC, imrekoszo commented
> Looks like we can merge this now

I'm okay with that!

2022-06-17 13:49 UTC, merged