Review and update README
polyfy/polylith pull request #327
Opened 2023-09-07 18:35 UTC by lread

As a noob, I did not at first understand Polylith was separate from the Clojure poly tool and documented separately. I made this clearer in the README.
- changed the title to include "for Clojure"
- I used the term "conceptual" instead of "high-level" for Polylith gitbook docs.

I got very confused by the diagram.
It is very cool but I thought it deserved at least a high level description. I might have got it right, please do review.

Was not shy about using the word Polylith.
In a README, I felt it deserved to be repeated often.

Other changes were minor, like splitting up long sentences.

2023-09-07 18:37 UTC, lread commented
@tengstrand, my first crack at the first file.

Lemme know what you think.
I'll not be offended at all if you want to make changes or don't like some of the changes I've made.

2023-09-08 05:08 UTC, tengstrand commented
Hi! I think you are right. You are right, the diagram looks cool, but is introduced too early. I suggest that we remove it on the first page (the readme). I like the change to conceptual. The diagram shows up in Production systems (I moved it from Example systems, and the 318-branch is one commit ahead of yours).

I like your changes, and it will make it easier for people to start out with Polylith!

Great work!

2023-09-08 05:47 UTC, tengstrand requested changes

2023-09-08 05:47 UTC, tengstrand commented on readme.adoc
> +Polylith can be implemented in any programming language.
I suggest that we skip this sentence entirely.

2023-09-08 12:15 UTC, lread commented on readme.adoc
> +Polylith can be implemented in any programming language.
Yeah, I think that make sense, it is now redundant.

2023-09-08 15:39 UTC, lread commented
@tengstrand made those changes. Happy to tweak more if you have more ideas.

2023-09-09 02:21 UTC, tengstrand requested changes

2023-09-09 02:21 UTC, tengstrand commented on readme.adoc
> +Clojure is a powerful and simple functional language for the https://en.wikipedia.org/wiki/Java_virtual_machine[JVM].
I think it flows better if we merge these two sentences "...describes the Polylith tool built for [Clojure](https://clojure.org/), which is a powerful ...
To get rid of the repetition "Clojure. Clojure".

2023-09-09 02:21 UTC, tengstrand commented on readme.adoc
> +Iron, Bronze, Silver, Gold, and Platinum sponsors are also listed and on the https://polylith.gitbook.io/polylith[front page of the Polylith docs].
Maybe it's enough to put the link in "front page": https://polylith.gitbook.io/polylith[front page] of the Polylith docs.

2023-09-09 03:08 UTC, lread commented on readme.adoc
> +Clojure is a powerful and simple functional language for the https://en.wikipedia.org/wiki/Java_virtual_machine[JVM].
I've personally got no problem with the 2 Clojures. 
I think smaller sentences are easier to digest.

2023-09-09 03:10 UTC, lread commented on readme.adoc
> +Clojure is a powerful and simple functional language for the https://en.wikipedia.org/wiki/Java_virtual_machine[JVM].
But, of course, your call.

2023-09-09 03:10 UTC, lread commented on readme.adoc
> +Iron, Bronze, Silver, Gold, and Platinum sponsors are also listed and on the https://polylith.gitbook.io/polylith[front page of the Polylith docs].
Sure, can do.

2023-09-09 03:15 UTC, lread commented on readme.adoc
> +Clojure is a powerful and simple functional language for the https://en.wikipedia.org/wiki/Java_virtual_machine[JVM].
Meh, I'll change it as suggested.

2023-09-09 03:18 UTC, lread commented on readme.adoc
> +Clojure is a powerful and simple functional language for the https://en.wikipedia.org/wiki/Java_virtual_machine[JVM].
Done!

2023-09-09 03:19 UTC, tengstrand commented on readme.adoc
> +Clojure is a powerful and simple functional language for the https://en.wikipedia.org/wiki/Java_virtual_machine[JVM].
Okay, thanks!

2023-09-09 03:21 UTC, merged