Review and update Install doc
polyfy/polylith pull request #331
Opened 2023-09-13 23:28 UTC by lread

Formatted overview on ways to install to a table.
For me this works better to compare variations.
It also helped me to fill in some missing blanks.
And to remove some details unnecessary for an overview (I moved some of these details down to specific install sections).
Let me know if this works for you too.

Noticed that overview mentions how to switch versions but install instructions do not talk about this. Did nothing about this yet.

Subtle: tried to use "we" only when talking from Polylith core team, and used "you" when talking to and guiding the reader.

Assumed poly core team preference is poly as stand-alone and/or Clojure CLI dep. Can adjust advice if this is not the case.
But making some clear suggestion avoids overwhelming newcomers.

Noticed some prerequisite and post-install advice repeated in some install instructions. But inconsistently. I moved these to adoc custom attributes so we have less copy/paste.

Now using adoc `subs="attributes+"` option in code blocks. This way code blocks can now reflect the `:poly-version:` attribute.

Moved clojure cli dep install instructions before clojure tools install instructions. This matches the overview order, and it (maybe?) the more likely order of interest for readers.

Added "stand-alone" to all headings that describe stand-alone installation. Just to make it extra clear.

Moved logging deps config to tools deps usage section as it only applies to that usage.

Re-orged Clojure Tools instructions a bit.
Clarified, I think, how it processes args.

Noticed that JVM options only applies to stand-alone variants to added that detail. I also noticed that it does not give an example, which I thought would be useful, but did nothing about that.

2023-09-13 23:31 UTC, lread commented
@tengstrand This one took some time to review. 
Let me know what you think, we can tweak it as needed.

2023-09-14 06:10 UTC, tengstrand requested changes

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +An alternative way of executing the `poly` tool is to specify it as a dependency in your `./deps.edn` file.
Most sentences use `our` instead of `your`, or `we` instead of `you`, as if we did this together. Change this to make it consistent.

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +== Install as Stand-alone on macOS
Do we need to use upper case for Stand-alone? I prefer stand-alone, if you don't have any strong opinions.

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +| Example usage
The text in this column (for all rows in the table) could be bold (to match the top headers) and end with a `:` e.g. **Example usage:**

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +=== Testing from Master
Change to "Run from master" or similar, because many users use the latest commit in master to get access to the latest functionality (not only for testing). Maybe Master can be in lower case, because the name of that branch is `master`?

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +This allows you to install any git revision poly and is often used to test out a version that has not been officially released yet:
I try to use `us` (and we) when possible instead of `you`, as if we are doing this together.

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +:post-install: pass:n[You will soon create your first xref:workspace.adoc[workspace] - for now, only `version`, `help`, `doc`, and `create workspace` commands will work.]
Change to "We will soon create our first...". I try to use `we` instead of `you` when possible, to emphasise that we are doing this together! (check the other occurrencies too)

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +For this reason, it can be convenient to first launch a `poly` shell so you can use the conventional `poly` command-line argument syntax.
`we` instead of `you`.

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +Let's say you want to get info on lines of code.
`we` instead of `you`

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +After which you can specify standard Polylith arguments:
`we`

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +                  _      _ + _   _
The ascii-art doesn't render nicely for me. Some characters are black, others are grey. One solution could be to change from `shell` to `text`. What is `attributes+` doing?

2023-09-14 06:10 UTC, tengstrand commented on doc/install.adoc
> +These can be conveyed via the `JVM_OPTS` environment variable which `poly` will passes along to the Java runtime at launch of poly stand-alone.
I think the logging example is relevant, for not-techie users (as me!).

2023-09-14 11:36 UTC, lread commented on doc/install.adoc
> +== Install as Stand-alone on macOS
No strong opinion at all, but capitalization for section titles should probably be consistent, whatever convention you choose.

2023-09-14 11:45 UTC, lread commented on doc/install.adoc
> +An alternative way of executing the `poly` tool is to specify it as a dependency in your `./deps.edn` file.
Yes, from my (admittedly huge) commit comment:

> Subtle: tried to use "we" only when talking from Polylith core team, and used "you" when talking to and guiding the reader.

My personal feeling is using "our" and "we" is a bit confusing and makes me sometimes wonder what "I" should be doing. It's subtle. I just did a web search and found this:
https://bernoff.com/blog/the-pronoun-conundrum-we-vs-you-in-business-advice

This is subjective and will adhere to your preference, lemme know.

2023-09-14 11:46 UTC, lread commented on doc/install.adoc
> +| Example usage
Sure, will do!

2023-09-14 11:52 UTC, lread commented on doc/install.adoc
> +=== Testing from Master
Good point, I did not mean to use "Testing" will switch as recommended.
See my previous question for section title capitalization.

Aside: I expect your repo was long created before https://www.bbc.com/news/technology-53050955, but some readers might be sensitive to the term master. Not making a suggestion here, just a comment.

2023-09-14 11:52 UTC, lread commented on doc/install.adoc
> +This allows you to install any git revision poly and is often used to test out a version that has not been officially released yet:
See previous comment on us and we.

2023-09-14 11:54 UTC, lread commented on doc/install.adoc
> +                  _      _ + _   _
Good catch. Will try changing code style to text.

See the commit comment for `attributes+`. This allows adoc attributes to be replaced in code block, in this case {poly-version}.

2023-09-14 11:56 UTC, lread commented on doc/install.adoc
> +These can be conveyed via the `JVM_OPTS` environment variable which `poly` will passes along to the Java runtime at launch of poly stand-alone.
See commit comment:

> Moved logging deps config to tools deps usage section as it only applies to that usage.

2023-09-14 12:23 UTC, lread commented on doc/install.adoc
> +== Install as Stand-alone on macOS
Maybe it is nice to capitalize headings "Like normal sentences"? I think that is fine too, lemme know.

2023-09-14 17:32 UTC, tengstrand commented on doc/install.adoc
> +An alternative way of executing the `poly` tool is to specify it as a dependency in your `./deps.edn` file.
Hmm, interesting! This is important, so let me check this and come back to you!

2023-09-14 17:34 UTC, tengstrand commented on doc/install.adoc
> +== Install as Stand-alone on macOS
Yes, capitalizing the headings, but lower case elsewhere.

2023-09-14 17:39 UTC, tengstrand commented on doc/install.adoc
> +=== Testing from Master
Good point. The default is `main` when you create a new Polylith workspace. I think we kept it to reduce complexity, don't remember (we had a discussion in the Polylith team).

2023-09-14 17:42 UTC, tengstrand commented on doc/install.adoc
> +These can be conveyed via the `JVM_OPTS` environment variable which `poly` will passes along to the Java runtime at launch of poly stand-alone.
Okay, cool.

2023-09-14 19:07 UTC, lread commented on doc/install.adoc
> +== Install as Stand-alone on macOS
So... to make sure I got it: for headings you'd like for example:

== The Dog and Cat are Friends

Instead of 

== The dog and cat are friends

(So Stand-alone would remain capitalized?)
I'm fine either way. Lemme know.

2023-09-14 19:44 UTC, lread commented
Ok @tengstrand: I've made a pass-through and addressed your feedback.

Known remaining items that I see:

- [ ] you vs we (lemme know when you've had a chance to discuss/decide)
- [ ] convention for heading capitalization (I still am not entirely clear what you want)

2023-09-16 05:54 UTC, tengstrand approved these changes
This looks really good and all changes make sense to me! I haven't check with my "English teacher friend" yet regarding the use of you/we, but I just decided to go with "your" style for now and use `you` as default. It's really hard to decide when to use `we` or `you`, so having `you` as default kind of makes sense because it's "never wrong" which `we` sometimes is. You can use `we` whenever that feels convenient, but let's figure this out later!

2023-09-16 05:55 UTC, merged