Review and update Upgrade doc
polyfy/polylith pull request #334
Opened 2023-09-15 19:27 UTC by lread

Done:
1. Don't immediately presume macOS.
2. Add a little generic text, from which I linked to other useful docs.
3. Match same install variations from Install doc
4. Add toc to match Install doc
5. Separate Linux and Windows (the grouping was convenient for author but not the reader).

Not done:
1. The is no mention of SNAPSHOT builds. A reader might wonder how to upgrade (not sure if this is even do-able for brew and nix):
   1. from a final release to a SNAPSHOT release
   2. from a SNAPSHOT release to a latest SNAPSHOT release under same version

2023-09-16 05:27 UTC, tengstrand requested changes
Made one comment, but except for that, it looks great with many improvements!

2023-09-16 05:27 UTC, tengstrand commented on doc/upgrade.adoc
> +Update your `polylith/clj-poly` dependency in your `deps.edn` to the current version.
I have a habit of writing `./deps.edn` if we refer to the deps.edn file at the workspace root (bricks and projects have their own).

2023-09-16 05:33 UTC, tengstrand commented
I think it's fine that this page only explains how to upgrade the stand-alone poly tool. I don't know yet how to upgrade a stand-alone pre-release of the poly tool, but perhaps we can revisit this page when we have made our first SNAPSHOT release.

2023-09-16 13:17 UTC, lread commented on doc/upgrade.adoc
> +Update your `polylith/clj-poly` dependency in your `deps.edn` to the current version.
Ya, that's a good convention, will do!

2023-09-16 13:21 UTC, lread commented
> I think it's fine that this page only explains how to upgrade the stand-alone poly tool.

To make sure I understand, are you suggesting I remove sections?:
- As Dependency
- Clojure CLI Tool

> I don't know yet how to upgrade a stand-alone pre-release of the poly tool, but perhaps we can revisit this page when we have made our first SNAPSHOT release.

Sounds good.

2023-09-16 14:08 UTC, tengstrand commented
> To make sure I understand, are you suggesting I remove sections?:
No, I was unclear. It's fine as it is!

2023-09-16 21:07 UTC, lread commented
@tengstrand, good to merge, I think.

2023-09-17 15:17 UTC, tengstrand approved these changes

2023-09-17 15:17 UTC, merged