Review and update Example Systems doc
polyfy/polylith pull request #336
Opened 2023-09-18 23:22 UTC by lread

Minor changes on this one.

Added a tip about the poly reports: to let the reader know what they are and that they will learn about them soon.

2023-09-19 19:01 UTC, tengstrand requested changes

2023-09-19 19:01 UTC, tengstrand commented on doc/example-systems.adoc
> +TIP: The reports on this page are all generated by the `poly` tool.
Almost true, but they are actually generated by the polyx tool which has its own page (polyx.adoc).

2023-09-19 19:42 UTC, lread commented on doc/example-systems.adoc
> +TIP: The reports on this page are all generated by the `poly` tool.
Thanks, will update!

2023-09-20 23:14 UTC, lread commented
@tengstrand, this one is ready for re-review and merge.

2023-09-21 20:30 UTC, merged