Review and update Component doc
polyfy/polylith pull request #342
Opened 2023-09-23 01:11 UTC by lread

Because most IDEs now support :local/root :extra-deps, moved this content out to its own section so it can more easily be skipped.

Don't assume all users are using Cursive.
Describe Cursive specific tip as such.

Otherwise, clarity and readability changes.

2023-09-23 04:59 UTC, tengstrand requested changes

2023-09-23 04:59 UTC, tengstrand commented on doc/component.adoc
> +* Or use the `:git-add` option with `poly` `create` commands.
I think this change made it harder to understand, and important information was removed, for example that the user has to explicitly pass in the `:git-add` parameter when using the create command to get the same effect as setting the parameter in the config. 
I'm unsure if "use the x option" is more clear also than talking about parameters to commands. Maybe "pass in" is not correct English, so that can maybe be improved.

2023-09-23 04:59 UTC, tengstrand commented on doc/component.adoc
> +There is also a fourth way to execute `poly` commands.
I think breaking up this short sentence makes the sentence flow less well, so I prefer "There is also a fourth way to execute `poly` commands, and that is to use the `poly` shell". But if you have a strong opinion about this, then keep it as it is.

2023-09-23 04:59 UTC, tengstrand commented on doc/component.adoc
> +From the poly shell, it's enough to enter the name of the command, e.g.:
If the text comes directly under an image, it's usually about that picture. But if it's about the next picture, I have added a line break, to make it more clear for the user that the text is about the next image.

2023-09-23 04:59 UTC, tengstrand commented on doc/component.adoc
> +TIP: Use `exit` to leave the `poly` shell.
...or press <cmd>+C or <cmd> + D.

2023-09-23 04:59 UTC, tengstrand commented on doc/component.adoc
> +The `create component` command created the user component `resources` directory:
I have been consistent throughout the documentation to always link to the command's help page, and here we should put the in on "create component".

2023-09-23 04:59 UTC, tengstrand commented on doc/component.adoc
> +There is no rule that the implementing namespace must be named `core`, but we chose that convention for this example.
The `core` namespace is created by the tool and is the default name of the implementing namespace, so I suggest that we change this sentence slightly.

2023-09-23 04:59 UTC, tengstrand commented on doc/component.adoc
> +If you want to compare the difference, take a look at how `article` was elegantly added as a single https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/5b6df23d63500a4540b7
I like that we move this section to the end, and the "elegantly added" change to the sentence!

2023-09-23 13:10 UTC, lread commented on doc/component.adoc
> +* Or use the `:git-add` option with `poly` `create` commands.
Oh, I thought this was a big improvement and much clearer.
I don't (yet) see the information loss.

Yes, "pass in" is awkward when talking about command lines.

Is your confusion with "parameter" vs "option"?  I thought these are command-line options.

2023-09-23 13:11 UTC, lread commented on doc/component.adoc
> +There is also a fourth way to execute `poly` commands.
I'll tend toward shorter sentences with the idea that they are easier to digest.
But I have absolutely no strong opinion here, so will join.

2023-09-23 13:14 UTC, lread commented on doc/component.adoc
> +From the poly shell, it's enough to enter the name of the command, e.g.:
Yes in another PR I mentioned I think we can fixup any image spacing issues in cljdoc itself so you would not need these compenstations.

2023-09-23 13:14 UTC, lread commented on doc/component.adoc
> +TIP: Use `exit` to leave the `poly` shell.
Would that work in Windows too?

2023-09-23 13:16 UTC, lread commented on doc/component.adoc
> +The `create component` command created the user component `resources` directory:
That's fine can do. I typically would be sure to link on the first mention, but linking on every mention is absolutely fine too.

2023-09-23 13:17 UTC, lread commented on doc/component.adoc
> +There is no rule that the implementing namespace must be named `core`, but we chose that convention for this example.
To add that fact? Sure, can do.

2023-09-23 13:18 UTC, lread commented on doc/component.adoc
> +If you want to compare the difference, take a look at how `article` was elegantly added as a single https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/5b6df23d63500a4540b7
Coolio, glad you like it.

2023-09-23 13:32 UTC, lread commented on doc/component.adoc
> +From the poly shell, it's enough to enter the name of the command, e.g.:
To give you an idea, here's how the asciidoctor tool renders spacing here:
![image](https://github.com/polyfy/polylith/assets/967328/7cb16a1a-9686-483a-bd66-b8d4211ad344)

Compared with current cljdoc rendering:
![image](https://github.com/polyfy/polylith/assets/967328/caa624a5-e303-45c9-b932-7a893916d066)

If I were to have cljdoc match the asciidoctor tool image spacing, I think your issue with spacing would go away. Am I right?

2023-09-23 13:33 UTC, lread commented on doc/component.adoc
> +* Or use the `:git-add` option with `poly` `create` commands.
Anyway, I want to make sure this is easy to understand, so keep typing, and we'll get there.

2023-09-23 13:37 UTC, lread commented
@tengstrand, thanks so much for your thoughtful review!

2023-09-23 13:40 UTC, lread commented on doc/component.adoc
> +There is also a fourth way to execute `poly` commands.
Also, are you reviewing in rich text? I find sometimes the adoc one-sentence-per-line can make things seem to flow less than they actually do.

2023-09-23 13:44 UTC, lread commented on doc/component.adoc
> +There is also a fourth way to execute `poly` commands.
Oh. Found something even better. I'll go with the much more succinct:

A fourth way to execute `poly` commands is through the `poly` shell.

2023-09-23 14:22 UTC, lread commented on doc/component.adoc
> +TIP: Use `exit` to leave the `poly` shell.
Maybe leave as is and describe other ways to exit in shell command docs?

Probably too much detail to describe <kbd>Ctrl</kbd> vs <kbd>Cmd</kbd> and then also describe what works on Windows.

2023-09-23 14:24 UTC, lread commented on doc/component.adoc
> +TIP: Use `exit` to leave the `poly` shell.
Oh there are docs on quit in shell.adoc. I'll link to that and we'll update those docs when we get there.

2023-09-24 04:01 UTC, tengstrand commented on doc/component.adoc
> +From the poly shell, it's enough to enter the name of the command, e.g.:
Yes, then I have no issue.

2023-09-24 13:32 UTC, lread commented on doc/component.adoc
> +From the poly shell, it's enough to enter the name of the command, e.g.:
Cool, I'll try to make the change on cljdoc sometime soon.

2023-09-24 15:26 UTC, lread commented on doc/component.adoc
> +* Or use the `:git-add` option with `poly` `create` commands.
How about: 
> Or specify the `:git-add` option on the `poly` `create` command.

Does that work better for you?

(create should also be a link).

2023-09-25 14:57 UTC, tengstrand commented on doc/component.adoc
> +* Or use the `:git-add` option with `poly` `create` commands.
Yes, that works!

2023-09-25 15:00 UTC, tengstrand commented on doc/component.adoc
> +You start the poly shell via the xref:commands.adoc#shell[shell] command.
Maybe we should end this sentence with a colon.

2023-09-25 19:48 UTC, tengstrand approved these changes

2023-09-25 19:49 UTC, merged