Review and update Interface doc
polyfy/polylith pull request #343
Opened 2023-09-23 22:36 UTC by lread

Add section headers.

Edits for clarity.

Some of the tips at the end of the doc were very confusing to me. After asking for clarification on Slack, rewrote some of them.

2023-09-24 04:36 UTC, tengstrand requested changes
Great improvements! They will definitely make the text easier to understand for users new to Polylith.

2023-09-24 04:36 UTC, tengstrand commented on doc/interface.adoc
> +Luckily, the Polylith tool will help us keep them consistent and complain if they differ when we run the xref:commands.adoc#check[check], xref:commands.adoc#info[info] or xref:commands.adoc#test[test
Her should use "the poly `tool`" (where poly is marked as code, which is also a convention through out the documentation). In the high-level doc we sometimes use "the Polylith tool" because that documentation is generic, but here we know that we talka about the `poly` tool. I forgot to change this, so this was not introduced by you.

2023-09-24 04:36 UTC, tengstrand commented on doc/interface.adoc
> +* It sometimes makes sense for a http://clojure-doc.org/articles/language/functions.html#multi-arity-functions[multi-arity function] in an interface to delegate to a single arity function in the impl
End the sentence with a colon (the same applies to the next point).

2023-09-24 04:36 UTC, tengstrand commented on doc/interface.adoc
> +By default, it will generate code using `interface` as the interface namespace name.
Add: ."when you crate a component." in the end

2023-09-24 04:36 UTC, tengstrand commented on doc/interface.adoc
> +*** or leave `interface` as the default and manually rename any generated `interface` to `ifc` for the components that will also run from ClojureScript.
We don't have to manually change the namespace here. Instead, we can give `interface:ifc` to the `create component` command, and it we use `ifc` instead as the interface name.

2023-09-24 08:34 UTC, tengstrand commented on doc/interface.adoc
Here somewhere, we could mention that the `poly` tool also checks that the signature must match exactly, for functions and macros. So if the parameter list is `[a b c]` for function `foo` it has to be defined as `[a b c]` in `foo` for all the implementing components. It means that `[b a c]` is not accepted. Type hints are also checked, e.g. if a function is defined as `[^String x y]`, we have define it as `[^String x y]` everywhere for that function. This reduces the risk that we enter the parameters in the wrong order.

2023-09-24 13:34 UTC, lread commented on doc/interface.adoc
> +Luckily, the Polylith tool will help us keep them consistent and complain if they differ when we run the xref:commands.adoc#check[check], xref:commands.adoc#info[info] or xref:commands.adoc#test[test
Yeah, that's a good convention. I'll update.

2023-09-24 13:36 UTC, lread commented on doc/interface.adoc
> +*** or leave `interface` as the default and manually rename any generated `interface` to `ifc` for the components that will also run from ClojureScript.
Good to know, will add.

2023-09-24 13:42 UTC, lread commented on doc/interface.adoc
These matching requirements are described above under the "Declaring the Same Interface in Multiple Components" section. I think it would be clearer if this whole tip was moved up to that section where it would be in context. 

I also like your explicit function signature examples, I'll work them in.
I expect I could make `defn` vs `defmacro` less wordy and clearer with examples.

2023-09-24 13:42 UTC, lread commented on doc/interface.adoc
> +* It sometimes makes sense for a http://clojure-doc.org/articles/language/functions.html#multi-arity-functions[multi-arity function] in an interface to delegate to a single arity function in the impl
Can do

2023-09-24 13:43 UTC, lread commented on doc/interface.adoc
> +By default, it will generate code using `interface` as the interface namespace name.
Can do

2023-09-25 15:42 UTC, tengstrand requested changes

2023-09-25 15:42 UTC, tengstrand commented on doc/interface.adoc
> +[cols="25,25,50"]
I really like this change of introducing a table here!

2023-09-25 15:42 UTC, tengstrand commented on doc/interface.adoc
> +The `util` component divides its https://github.com/polyfy/polylith/tree/master/components/util/src/polylith/clj/core/util/interface[interface] into several sub-namespaces:
Here I prefer one sentence, because they are so coupled to each other:
You can find an example in Polylith itself, where the `util` component divides its...

2023-09-25 15:42 UTC, tengstrand commented on doc/interface.adoc
> +Here's an example of the sub-interface usage from the https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/master/bases/rest-api/src/clojure/realworld/rest_api/handler.clj[R
End the sentence with "base" (that links to the `base` page):
...in it's `rest-api` base:

2023-09-25 15:42 UTC, tengstrand commented on doc/interface.adoc
> +The implementing function can expose specific usage via destructuring, e.g., `sell [{:keys [model type color]}]`.
Here the comparison is lost when we split the sentence in two. I recommend to put back "while" again, to make it clearer that they have two different roles.

2023-09-25 16:50 UTC, lread commented on doc/interface.adoc
> +[cols="25,25,50"]
Glad you like it too!

2023-09-25 16:52 UTC, lread commented on doc/interface.adoc
> +The `util` component divides its https://github.com/polyfy/polylith/tree/master/components/util/src/polylith/clj/core/util/interface[interface] into several sub-namespaces:
Yeah, I think we'll continue to have a healthy back-and-forth on sentence length.
I see no problem with joining here.

2023-09-25 16:52 UTC, lread commented on doc/interface.adoc
> +Here's an example of the sub-interface usage from the https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/master/bases/rest-api/src/clojure/realworld/rest_api/handler.clj[R
Can do

2023-09-25 16:55 UTC, lread commented on doc/interface.adoc
> +The implementing function can expose specific usage via destructuring, e.g., `sell [{:keys [model type color]}]`.
I find it clearer with 2 sentences.
They are in the same paragraph, after all.
But I think we are on subjective grounds here maybe? So also fine with joining them.
If only we had an English teacher to chime in! :slightly_smiling_face:

2023-09-25 17:10 UTC, lread commented on doc/interface.adoc
> +The implementing function can expose specific usage via destructuring, e.g., `sell [{:keys [model type color]}]`.
Hmm... maybe you are right. That does seem to read better!

2023-09-25 19:44 UTC, tengstrand approved these changes

2023-09-25 19:44 UTC, merged