Let readers know doc improvements are a wip
polyfy/polylith pull request #344
Opened 2023-09-25 16:47 UTC by lread

2023-09-25 20:04 UTC, tengstrand requested changes

2023-09-25 20:04 UTC, tengstrand commented on readme.adoc
> +NOTE: *Work in Progress*: While we are very proud of our documentation, we are currently working to make it even better!
Perhaps we should add information that this documentation is a SNAPSHOT build from the issue-318 branch (with a link to the polylith repository for that branch). Otherwise, it will not be obvious which code it corresponds to, when you run the cljdoc version of it.

We could also (maybe) mention that in the future, all SNAPSHOT releases will be built from the `master` branch, but right now it's from `issue-318`.

2023-09-25 21:23 UTC, lread commented on readme.adoc
> +NOTE: *Work in Progress*: While we are very proud of our documentation, we are currently working to make it even better!
I was thinking keeping it vague was nice in that it would let you merge at any time without changing any text.

But, that's fine, I'll add in those details.

You'll just have to remember to update the text before the final merge to master!

2023-09-27 02:10 UTC, tengstrand approved these changes

2023-09-27 02:11 UTC, merged