Review and update Base doc
polyfy/polylith pull request #346
Opened 2023-09-26 23:33 UTC by lread

Edits for clarity.

Distinguish cursive advice by making it a tip.

Experiment with AsciiDoc code callouts.
We'll backtrack and add them to previously reviewed docs if they seem to add value. (I think they do).

2023-09-27 02:18 UTC, tengstrand requested changes

2023-09-27 02:18 UTC, tengstrand commented on doc/base.adoc
> +This is fine; the sole purpose of a `base` is to act as a bridge between the real world and the xref:component.adoc[component] it delegates to.
Should be "...components it delegates to" (plural).

2023-09-27 05:20 UTC, tengstrand commented on doc/base.adoc
> +This is fine; the sole purpose of a `base` is to act as a bridge between the real world and the xref:component.adoc[component] it delegates to.
"components it delegate to"

2023-09-29 13:32 UTC, lread commented
@tengstrand ready for merge, or do you have more feedback?

2023-09-29 22:25 UTC, tengstrand requested changes

2023-09-29 22:25 UTC, tengstrand commented on doc/base.adoc
> +A `base` gives us the modularity and structure we need to build simple, understandable services and tools.
I prefer "This gives us", because it's the collaboration between bases and components (the delegation to them via interfaces) that gives us the modularity, not just the bases alone.

2023-09-29 22:25 UTC, tengstrand commented on doc/base.adoc
> +Run the following xref:commands.adoc#create-base[create base] command to create a `cli` `base`:
I would prefer to only have `cli` marked as code, because that's the thing that is interesting in this context.

2023-09-29 22:25 UTC, tengstrand commented on doc/base.adoc
> +Edit your workspace `./deps.edn` to add your newly created `base`:
I think we can use base instead of `base` here.

2023-09-29 22:35 UTC, lread commented on doc/base.adoc
> +A `base` gives us the modularity and structure we need to build simple, understandable services and tools.
Ah right, my grammar checker said that the reader might not know what "This" refers to.
My guess was wrong!

So the reader does not have to guess, instead maybe?:
"This structure gives us the modularity we need to build simple, understandable services and tools"

2023-09-29 22:37 UTC, lread commented on doc/base.adoc
> +Run the following xref:commands.adoc#create-base[create base] command to create a `cli` `base`:
Yeah, I'm confused about what should be marked as code and what should not.
Let's work out a convention on slack and document it.

2023-09-29 22:37 UTC, lread commented on doc/base.adoc
> +Edit your workspace `./deps.edn` to add your newly created `base`:
See last comment

2023-09-30 08:08 UTC, tengstrand commented on doc/base.adoc
> +This is fine; the sole purpose of a `base` is to act as a bridge between the real world and the xref:component.adoc[components] it delegates to.
After "it delegates to", add "via the component's interfaces".

2023-09-30 08:19 UTC, tengstrand commented on doc/base.adoc
> +This is fine; the sole purpose of a `base` is to act as a bridge between the real world and the xref:component.adoc[components] it delegates to.
Maybe in parenthesis.

2023-09-30 08:23 UTC, tengstrand commented on doc/base.adoc
> +Run the following xref:commands.adoc#create-base[create base] command to create a `cli` `base`:
The convention could be that we don't mark the interface/component/base/project as code from the same page as the "entity", e.g. from base.adoc, we don't refer to base as `base`. An exception could be the first time we introduce it (`base` in this example) but that should be optional, and only used if we think it adds clarity.

2023-09-30 13:35 UTC, lread commented on doc/base.adoc
> +Run the following xref:commands.adoc#create-base[create base] command to create a `cli` `base`:
Ok, so for example, for the base doc, we format as `base` for the first usage.
Other key concepts like [interface](#) or [component](#) will be links, so we don't have to worry about those.

But... we might find that always linking is a bit distracting (and of little value) if over-used for the same term.
For example, if we are talking about [interface](#) a bunch we probably want to instead use code formatting for subsequent uses of `interface` if nearby the link.
Or if that is distracting, use plaintext interface for subsequent uses.

Concrete rules are easier to follow... but does that work for you?

2023-09-30 13:39 UTC, lread commented on doc/base.adoc
> +Run the following xref:commands.adoc#create-base[create base] command to create a `cli` `base`:
Actually, let's go with plaintext for nearby subsequent uses of, from the above example, interface. 

All sound good?

2023-10-01 03:25 UTC, tengstrand approved these changes
Looks great!

2023-10-01 03:25 UTC, merged