Review and update Shell doc
polyfy/polylith pull request #351
Opened 2023-10-02 15:30 UTC by lread

Added more headings.

Added more hand-holding, explanations and terminal examples.

It is nice to learn how to quit early.
Moved section right after instructions on how to launch.

Added necessary pre-steps for folks who want to try out switch-ws examples.

Edits for clarity.

2023-10-03 05:31 UTC, tengstrand requested changes
Nice work, and great improvements!

2023-10-03 05:31 UTC, tengstrand commented on doc/component.adoc
> +* Manually `git add` files generated by xref:commands.adoc#create[create] commands yourself.
Maybe we could add a link here to https://git-scm.com/docs/git-add, so that it gets even more clear what we are talking about?

2023-10-03 05:31 UTC, tengstrand commented on doc/shell.adoc
> +TIP: Our examples assume you are exploring from our ongoing tutorial `example` xref:workspace.adoc[workspace].
I like that we add a tip here. We could also add a link to the final version of the example, and inform the user that we have it [here](https://github.com/polyfy/polylith/tree/issue-318b/examples/doc-example).

2023-10-03 05:31 UTC, tengstrand commented on doc/shell.adoc
> +NOTE: You can export a workspace to a `.edn` file, e.g. via `poly ws out:ws.edn`.
We use `ws.edn` almost everywhere in the examples. We could use `realworld.edn` as an example, just to give an example that the file can have any name.

2023-10-03 05:31 UTC, tengstrand commented on doc/shell.adoc
>                    _      _ + _   _
As you said before, I think in Slack, we should replace these two ascii versions. I can do that after this page has been approved (I put that on my todo list).

2023-10-03 05:31 UTC, tengstrand commented on doc/shell.adoc
> +== Autocomplete Examples
I really like this improvement, with examples added!

2023-10-03 12:54 UTC, lread commented on doc/component.adoc
> +* Manually `git add` files generated by xref:commands.adoc#create[create] commands yourself.
Yes, that would probably help. Will do!

2023-10-03 12:59 UTC, lread commented on doc/shell.adoc
> +TIP: Our examples assume you are exploring from our ongoing tutorial `example` xref:workspace.adoc[workspace].
Maybe we should talk about the tutorial example in some detail very early in the docs.
Then we can link back to that description from later tips. This could be a todo in #348.

2023-10-03 12:59 UTC, lread commented on doc/shell.adoc
> +NOTE: You can export a workspace to a `.edn` file, e.g. via `poly ws out:ws.edn`.
Sounds good, will do!

2023-10-03 13:02 UTC, lread commented on doc/shell.adoc
>                    _      _ + _   _
Yeah probably. I guess it really only stands out when the big Polylith logo is present.

2023-10-03 13:07 UTC, lread commented on doc/shell.adoc
> +== Autocomplete Examples
Thanks, I was thinking these particular examples don't really need to be screenshots.
None of them include the big Polylith logo. We do miss out on the cursor, but at this point in the docs, that is probably not terribly important?

I suppose we could use the unicode █ if we really want that cursor in there.

```
example$ hello █
```
What do you think?

2023-10-03 18:39 UTC, tengstrand commented on doc/shell.adoc
> +== Autocomplete Examples
I think they are fine as they are, and we can skip the extra cursor also.

2023-10-05 21:13 UTC, lread commented on doc/shell.adoc
> +TIP: Our examples assume you are exploring from our ongoing tutorial `example` xref:workspace.adoc[workspace].
Added a todo to #348

2023-10-05 21:20 UTC, lread commented on doc/shell.adoc
> +NOTE: You can export a workspace to a `.edn` file, e.g. via `poly ws out:ws.edn`.
Oh but we are talking about usermanager for this example, so I'll use `usermanager.edn`.

And this affects a shell screenshot, I'll just use text for it instead.

2023-10-05 21:27 UTC, lread commented on doc/shell.adoc
> +== Autocomplete Examples
Cool!

2023-10-05 21:29 UTC, lread commented
@tengstrand I responded to all review feedback addressed to me!

2023-10-06 02:41 UTC, tengstrand approved these changes
Looks great!

2023-10-06 02:47 UTC, merged