Review and update Build doc
polyfy/polylith pull request #369
Opened 2023-10-11 20:49 UTC by lread

Mention tutorial.

Mention what Clojure tools.build is.

Add call-outs to build.clj.

Remove `io.github.seancorfield/build-uber-log4j2-handler` from docs and example build.clj. It is a useful lib but not specifically needed for our example.

Point to `build.clj` associated with release instead of master HEAD version.

Don't assume everybody is using Cursive: move help to tip.

Edits for clarity.

2023-10-11 22:12 UTC, tengstrand requested changes

2023-10-11 22:12 UTC, tengstrand commented on examples/doc-example/build.clj
> -                              ;; if your project (or any of its dependencies)
Also make the same deletion from `scripts/sections/build/build.clj`.

2023-10-11 22:17 UTC, tengstrand commented on doc/build.adoc
> +Whether you choose simple build scripts or cloud-based build tools, `poly` does not get in the way.
Maybe use doesn't.

2023-10-11 22:18 UTC, lread commented on doc/build.adoc
> +Whether you choose simple build scripts or cloud-based build tools, `poly` does not get in the way.
Will do.

2023-10-11 22:18 UTC, lread commented on examples/doc-example/build.clj
> -                              ;; if your project (or any of its dependencies)
Ah did not see that one, will do.

2023-10-12 19:34 UTC, lread commented
@tengstrand: all review feedback addressed!

2023-10-12 20:49 UTC, tengstrand approved these changes

2023-10-12 20:50 UTC, merged