Add Greenlabs to production-systems doc
polyfy/polylith pull request #372
Opened 2023-10-17 09:59 UTC by namenu

Add a new case to the Production Systems page.

Let me know if there's anything else you'd like me to include.

cc. @yyna

2023-10-17 18:57 UTC, tengstrand requested changes

2023-10-17 18:57 UTC, tengstrand commented on doc/production-systems.adoc
> +
It would be good if you could include the image also (see how it's done by the other companies), e.g.:

image::images/production-systems/greenlabs.png[link="images/production-systems/greenlabs.png"]

2023-10-17 18:57 UTC, tengstrand commented on doc/production-systems.adoc
> +
It would also be good if you could move it up, so that it comes after World Singles Networks, but before Polylith.

It would also be nice if you could add aliases to your projects (but that's up to you) to make the projects more readable, e.g.:
- `aws-lambda-braze`, could have the alias `brz` or `braze`
- `aws-lambda-cach-receipt-update, could get the alias `cru`
- and so on...instead of showing the default values ?1, ?2, ?3...

2023-10-18 02:39 UTC, namenu commented on doc/production-systems.adoc
> +
Normally, I removed aliases because they don't seem to improve readability, but in this case I agree that the image visibility wasn't good. Added aliases along with gpt :)

2023-10-18 05:12 UTC, tengstrand commented on doc/production-systems.adoc
> +
Great! You use different version of the same libraries, e.g. buddy-sign, com.cognitect.aws/api, and others. I have no problems with leaving it that way, but it would look better if you use the same version of each library everywhere.

2023-10-18 12:08 UTC, namenu commented on doc/production-systems.adoc
> +
Yeah, diverging library versions is the problem we have..
I can make it more consistent, but it think it will take some time.

2023-10-18 14:52 UTC, tengstrand commented on doc/production-systems.adoc
> +
I merge this, and then you can add another PR later! It's an impressive workspace you have. Really cool that you wanted to share it.

2023-10-18 14:52 UTC, merged