Review & Update Flags, Testing, Test Runners docs
polyfy/polylith pull request #377
Opened 2023-10-29 14:44 UTC by lread

General
- Noticed I had accidentally changed `command-line` project alias from `cl` to `cli`, so addressed that in project.adoc.
- Edits for clarity.
- Info snapshot images are now often annotated, usually just with an orange box to focus the reader on the part of the output we are describing. Since the snapshots images are generated automatically via a script, I've decided to link to the generated image from the manually annotated InkScape svg. I'll circle back in a future PR to look at the script that generates these snapshots and see what we can improve.

Flags doc
- Describe flags in general
- Add section headings and doc
- Re-order brick flags content to match order of project flags
- Do more hand-holding in flags with the help of new `info` output images that point to what we are describing.

Testing doc
- Added some upfront description on how poly runs tests which should help newcomers.
- Annotated info images with focus boxes
- Fixed a fn name typo in setup/teardown examples

Test Runners doc
- re-orged to cover what the average reader might be first interested in
- used Sean's and Imre's test runners in examples so reader can actually try something concrete out.
- clarified that poly only includes an in-process test runner

2023-10-29 14:47 UTC, lread commented
Ok @tengstrand, this is a big one, and I expect it will take a while for you to review.
Please review the commit comment for an overview.
I filled in information gaps with my understanding; please review carefully to make sure my understanding is actually correct!

2023-10-30 05:45 UTC, tengstrand requested changes

2023-10-30 05:45 UTC, tengstrand commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in the workspace `./deps.edn`
Should be: isn't referenced in the development `./deps.edn` file (or similar, not workspace).

2023-10-30 05:45 UTC, tengstrand commented on doc/flags.adoc
> +. `./projects/command-line/test` isn't referenced in the workspace `./deps.edn`
development, not workspace

2023-10-30 05:45 UTC, tengstrand commented on doc/flags.adoc
> +There are four possible flags:
For me this became more complicated, that we now try to introduce both the project flags and the brick flags at the same time. I like the boxes around each area, but maybe we could introduce projects first (with just one box) and then the bricks section later, also with one box.

If we do that, we could be more precise in the descriptions.
Then we could say things like:
`s` means a project's `src` directory is included in the project, otherwise `-`.
`t` means a project's `test` directory is included in the project, otherwise `-`.
 
In the bricks section we can say:
`s` means a component's `src` directory is included in the project, otherwise `-`.
`t` means a component's `test` directory is included in the project, otherwise `-`.

When we create a brick, the tool creates a `src`, `resources` and `test` directory for us, and a `deps.edn` file, where the `src` and `resources` directories are specified in `:paths` as `["src" "resources"]`, and the `test` directory as `["test"]` in `:aliases > :test > :extra-paths`. 

But we are free to change the name of the `src` directory, or store the source in more than one directory, e.g.
`["src2" "cljc" "resources"]`, or `["test1" "test2]` for the test context.

The `resources` directory is an exception, which has to have exactly that name.

I suggest that we talk about `src` and `test` everywhere, to make it simpler, and then at the end we can have an info box that clarifies that it's more flexible.

Also, talking about `true` and `false` maybe just make the reader more confused. Maybe we should change from "Flags" to "Status flags" or something, but I'm not sure about that.

2023-10-30 11:42 UTC, lread commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in the workspace `./deps.edn`
Because there are many `deps.edn` files, my feeling is that using `./deps.edn` isn't clear enough for the reader. I've been calling this `deps.edn` the "workspace `./deps.edn`", [example](https://github.com/polyfy/polylith/blob/b3dcc8bbb315dfd2a9b8d011c3195c4b617ffd0b/doc/project.adoc?plain=1#L8). Are you suggesting we call it the "development `./deps.edn`"? Or maybe "development project `./deps.edn`"?

2023-10-30 11:42 UTC, lread commented on doc/flags.adoc
> +. `./projects/command-line/test` isn't referenced in the workspace `./deps.edn`
see above reply

2023-10-30 12:04 UTC, lread commented on doc/flags.adoc
> +There are four possible flags:
> For me this became more complicated, that we now try to introduce both the project flags and the brick flags at the same time. I like the boxes around each area, but maybe we could introduce projects first (with just one box) and then the bricks section later, also with one box.

And

> Also, talking about true and false maybe just make the reader more confused. Maybe we should change from "Flags" to "Status flags" or something, but I'm not sure about that.

Hmm... I'm not sure I understand the confusion yet.

We can assume a `poly` user is a programer and clearly understands booleans and `true` and `false`. Do you think maybe because you've been working on the higher level docs there is a change you might be thinking from a different perspective?

Coming in as a newbie, I have absolutely no clue what flags are. 
Do you think it is confusing to describe them as a general concept first and then ease into the details?

> When we create a brick, the tool creates a src, resources and test directory for us, and a deps.edn file, where the src and resources directories are specified in :paths as ["src" "resources"], and the test directory as ["test"] in :aliases > :test > :extra-paths.

> But we are free to change the name of the src directory, or store the source in more than one directory, e.g.
["src2" "cljc" "resources"], or ["test1" "test2] for the test context.

> The resources directory is an exception, which has to have exactly that name.

> I suggest that we talk about src and test everywhere, to make it simpler, and then at the end we can have an info box that clarifies that it's more flexible.

Yes, good points. I notice that somewhere else the docs talk about the src and test "contexts". But are there terms the Clojure core team uses for this concept? 
I guess technically, it comes down to the classpath, yes? The default classpath and the `test` alias classpath?

2023-10-30 17:13 UTC, tengstrand commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in the workspace `./deps.edn`
Yes, "development project `./deps.edn`" sounds good to me.

2023-10-30 20:09 UTC, lread commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in the workspace `./deps.edn`
Sounds good, will update.

2023-10-30 20:22 UTC, lread commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in the workspace `./deps.edn`
Hmmm.... as I am making this change, I'm finding it might confuse the reader who is not very familiar with what the development project is. They might assume it is in some other dir. 

Although incorrect, "workspace `./deps.edn`" implied its location.

I think your original strategy of just `./deps.edn` (without any descriptors) might be the least confusing. Unless you have other ideas?

2023-10-31 14:25 UTC, lread commented on doc/flags.adoc
> +There are four possible flags:
@tengstrand So, I think after Slack discussions, and input from others, we are now OK with the general description of flags?  

I think your feedback about the `src` and `test` paths is still worth exploring.
I can try to work on a change that explains this.

2023-11-03 19:25 UTC, lread commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in the workspace `./deps.edn`
Ok, from Slack, @tengstrand has agreed to go with an unadorned `./deps.edn`.

2023-11-03 19:56 UTC, lread commented on doc/flags.adoc
> +There are four possible flags:
Add note on src and test paths.

2023-11-03 20:02 UTC, lread commented
Ok @tengstrand, all known/remembered feedback addressed.

2023-11-04 05:36 UTC, tengstrand requested changes

2023-11-04 05:36 UTC, tengstrand commented on doc/testing.adoc
> +Now add this same path to your workspace `./deps.edn`:
Change to "development project `./deps.edn`

2023-11-04 05:36 UTC, tengstrand commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in the workspace `./deps.edn`
It is the config file for the development project. Maybe people know that already, so then we may skip that information.

2023-11-04 05:36 UTC, tengstrand commented on doc/flags.adoc
> +There are four possible flags:
Yes, let's go with the general description of flags. 
"I can try to work on a change that explains this." - yes if you want to. I still feel that we can be more crisp about this.

2023-11-04 05:36 UTC, tengstrand commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in ./deps.edn`
Missing back-tick for ./deps.edn

2023-11-04 21:42 UTC, lread commented on doc/flags.adoc
> +. `./projects/command-line/src` isn't referenced in ./deps.edn`
Tx

2023-11-04 21:43 UTC, lread commented on doc/testing.adoc
> +Now add this same path to your workspace `./deps.edn`:
Pretty sure this is done with prev commit.

2023-11-05 06:10 UTC, tengstrand approved these changes
Thanks for this!

2023-11-05 06:10 UTC, merged