Review and update Profile doc
polyfy/polylith pull request #388
Opened 2023-11-14 19:45 UTC by lread

Describe the purpose of profiles early and succinctly (and hopefully, correctly!).

Add separate InkScape SVGs for all hand-crafted diagrams. Adapted from source SVG provided by Joakim.
Switched to cross-OS friendly fonts in SVGs.
Resized boxes and fonts for consistency across all images. Added dotted box around Development and Production environments for extra clarity.
Cljdoc does not have a dark theme, but GitHub does, so I put some effort into making images dark-theme-friendly.

Hand-crafted SVG image text is now more explicit to avoid ambiguity. Added suffixes "Env" (for environments), "project", and "profile".

Annotated info screenshots with orange boxes to focus the reader output relevant to docs.

No longer assuming everybody uses Cursive by moving Cursive specific guidance to adoc tips.

With the idea that simpler is better for our examples, reduced number of logging libraries used in examples from 2 to 1.

Added one more `poly info` example to show default profile selection.

Added sections and toc.

And many other changes.

2023-11-14 20:45 UTC, tengstrand requested changes

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +TIP: You likely don't need porfiles if your xref:workspace.adoc[workspace] does not include xref:interface.adoc#one-interface-in-multiple-components[duplicate interfaces].
typo: porfiles

The interfaces are not duplicated, so we need to rephrase this, e.g. that they have interfaces that are implemented by more than one component.

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +* in production because `command-line` and `user-remote` projects naturally run in separate processes.
... and `user-service` (not `user-remote`)

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +* when xref:testing.adoc[testing] via `poly` because xref:test-runners.adoc[test-runners] provide classpath isolation at the project level.
At this stage we would have class path problems for the `development` project, because both `user` and `user-remote` are included in that project. 
Maybe we could remove this info box or rephrase it, to say something that that we can't include two or more components that implement the same interface in any project (`development` included).

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +image::images/profile/profiles-in-dev.png[]
I liked that it was some space between default/remote and the two development projects, so that "development + default or remote" comes on a single line, and then after "=", the two resulting development projects comes on a new "clean" line, and that they don't partially share the line with the above development project.

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +<2> Add logging libraries (slacker lib does some logging that we'll ignore)
Add logging library (singular)

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +<3> Add logging libraries (slacker lib does some logging that we'll ignore)
change to singular

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +image::images/profile/compare-with-target-design-annotated.png[]
I love this new image!

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +You can override the default protocol by specifying a protocol:
profile, not protocol

2023-11-14 20:45 UTC, tengstrand commented on doc/profile.adoc
> +image::images/profile/info-with-remote-profile-annotated.png[width=500]
These images are great!

2023-11-14 21:39 UTC, lread commented on doc/profile.adoc
> +TIP: You likely don't need porfiles if your xref:workspace.adoc[workspace] does not include xref:interface.adoc#one-interface-in-multiple-components[duplicate interfaces].
tx

2023-11-14 21:39 UTC, lread commented on doc/profile.adoc
> +* in production because `command-line` and `user-remote` projects naturally run in separate processes.
tx

2023-11-14 21:43 UTC, lread commented on doc/profile.adoc
> +* when xref:testing.adoc[testing] via `poly` because xref:test-runners.adoc[test-runners] provide classpath isolation at the project level.
I like explaining that this is only a `development` project concern and *why* it is not a production and testing concern. But maybe my intent was not clear?

2023-11-14 21:46 UTC, lread commented on doc/profile.adoc
> +image::images/profile/profiles-in-dev.png[]
Old image:
![image](https://github.com/polyfy/polylith/assets/967328/998e6b53-70b9-481c-b7a2-c372e1a5b33e)

New image:
![image](https://github.com/polyfy/polylith/assets/967328/8ee0db49-7064-4d69-8495-45eb114255b5)

Ah, I think you mean vertical space. I don't fully see the importance, but easier for me to just do it than discuss it!

2023-11-14 21:46 UTC, lread commented on doc/profile.adoc
> +<2> Add logging libraries (slacker lib does some logging that we'll ignore)
Ah yes, tx.

2023-11-14 21:47 UTC, lread commented on doc/profile.adoc
> +<3> Add logging libraries (slacker lib does some logging that we'll ignore)
tx

2023-11-14 21:47 UTC, lread commented on doc/profile.adoc
> +image::images/profile/compare-with-target-design-annotated.png[]
Thank you!

2023-11-14 21:47 UTC, lread commented on doc/profile.adoc
> +image::images/profile/info-with-remote-profile-annotated.png[width=500]
Thank you!

2023-11-14 21:48 UTC, lread commented on doc/profile.adoc
> +You can override the default protocol by specifying a protocol:
Goodness me, yes, editing these docs can make me cross-eyed after a while. Tx!

2023-11-14 22:32 UTC, lread commented on doc/profile.adoc
> +image::images/profile/profiles-in-dev.png[]
I think I see your point now. It should look more like a math addition in a school book.
Updated:
![image](https://github.com/polyfy/polylith/assets/967328/1eef50a7-1aa8-455d-8ea8-7b3d010041f1)

2023-11-14 22:33 UTC, lread commented on doc/profile.adoc
> +* when xref:testing.adoc[testing] via `poly` because xref:test-runners.adoc[test-runners] provide classpath isolation at the project level.
I tweaked the text a bit, let me know what you think.

2023-11-14 22:40 UTC, lread commented on doc/profile.adoc
> +TIP: You likely don't need porfiles if your xref:workspace.adoc[workspace] does not include xref:interface.adoc#one-interface-in-multiple-components[duplicate interfaces].
> The interfaces are not duplicated, so we need to rephrase this, e.g. that they have interfaces that are implemented by more than one component.

Changed wording from duplicate, lemme know what you think.

2023-11-14 22:41 UTC, lread commented
@tengstrand, thanks for the thoughtful feedback, I left conversations open that require another review from you.

2023-11-15 03:27 UTC, tengstrand approved these changes

2023-11-15 03:28 UTC, merged