Review and update Libraries doc
polyfy/polylith pull request #391
Opened 2023-11-18 21:25 UTC by lread

Generate libs, libs :compact, and libs with overriden dep from create_example.clj.

Add support to create-example to run a subset of tasks by a group id. Running all tasks can take several minutes, so it is handy to be able to, for example, run `bb create-example realworld` to only run the realword tasks. If no group ids are specified, all tasks are run.

Added more sections and a table of contents.

The word "dependencies" is overloaded because we call a brick a "dependency" but a 3rd-party library is also a "dependency". I tried to soften the confusion by adding a few words.

Re-organized content to start with something the reader can easily try out then dug progressively into details.

Edits for clarity.

2023-11-18 21:26 UTC, lread commented
@tengstrand Here's my crack at the Libraries doc.
As always, please read the commit comment before reviewing.

2023-11-19 07:19 UTC, tengstrand requested changes
Except from one thing, everything looks great!

2023-11-19 07:19 UTC, tengstrand commented on doc/libraries.adoc
> +For example:
Looks like there is a missing example here.

2023-11-19 15:37 UTC, lread commented on doc/libraries.adoc
> +For example:
Oh thanks! I accidentally left the old example prompt in there with my simplified replacement. Will fix.

2023-11-19 15:53 UTC, lread commented on doc/libraries.adoc
> +For example:
Fixed!

2023-11-19 15:53 UTC, lread commented
@tengstrand I've addressed your review feedback.

2023-11-19 16:53 UTC, tengstrand approved these changes

2023-11-19 16:53 UTC, tengstrand commented on doc/libraries.adoc
> +For example:
Cool!

2023-11-19 16:54 UTC, merged