Review and update Configuration doc
polyfy/polylith pull request #395
Opened 2023-11-20 21:47 UTC by lread

Introduce user and poly config as separate categories.

Include filename in section headings.

Group all deps.edn config section headings under a new section heading.

Explain how each config file is initially created and how it is changed.

Clearly mark derived configuration.

Show default config values when appropriate.

Add note that output in doc might not always match output if following along in tutorial (for illustrative purposes).
That said, update output to better match actual output.

Ensure that `:key-names` do not wrap in tables.

Link to other docs when helpful.

Fix some typos.

Edits for clarity.

2023-11-20 21:48 UTC, lread commented
@tengstrand, ready for review and feedback!
As always, please read the commit comment carefully before reviewing.

2023-11-21 04:38 UTC, tengstrand requested changes
Nice changes!

2023-11-21 04:38 UTC, tengstrand commented on doc/configuration.adoc
> +a| Supports turning off `Warning 206` for one or more bricks; see xref:validations.adoc#ignore-files[Validations]. +
This has recently changed to `Error 111`. I also realise that I have missed updating the Validations.adoc file and a couple of more places. You can leave those updates to me if you want!

2023-11-21 04:38 UTC, tengstrand commented on doc/configuration.adoc
> +a| Supports turning off `Warning 206` for one or more bricks; see xref:validations.adoc#ignore-files[Validations].
Change to `Error 111`.

2023-11-21 04:38 UTC, tengstrand commented on doc/configuration.adoc
> +You make changes via manual edits or the xref:libraries#update[libs update] command.
Change to `libs :update`.

2023-11-21 04:38 UTC, tengstrand commented on doc/configuration.adoc
> +Each xref:component.adoc[component] tools.deps config is found in `components/_COMPONENT-DIR_/deps.edn` where `_COMPONENT_DIR_` is the component's directory (and name).
Should be _COMPONENT-DIR_ in both places.

2023-11-21 16:04 UTC, lread commented on doc/configuration.adoc
> +You make changes via manual edits or the xref:libraries#update[libs update] command.
good catch, tx, will update

2023-11-21 16:05 UTC, lread commented on doc/configuration.adoc
> +Each xref:component.adoc[component] tools.deps config is found in `components/_COMPONENT-DIR_/deps.edn` where `_COMPONENT_DIR_` is the component's directory (and name).
tx, will update

2023-11-21 16:10 UTC, lread commented
Ok @tengstrand, I merged in your changes and addressed all review feedback!

2023-11-21 18:31 UTC, tengstrand approved these changes

2023-11-21 18:31 UTC, merged