Review and Update Source Code doc
polyfy/polylith pull request #398
Opened 2023-11-22 19:57 UTC by lread

Added table of contents.

The first block of text talks specifically about multiple paths but had no heading, so added one.

I downplayed .clj vs .cljc code organization in first section to be an illustrative of multiple paths. (To me, the text seemed to be recommending separate `clj` and `cljc` dirs was some sort of poly recommendation, which felt odd.)

Reworded a some text under the frontend section.
The term "stripped" did not mean much to me, so I tried to instead explain.
The term "import" was problematic because it will be confused with Clojure's `import` so reworded that too.

Other edits for clarity.

2023-11-22 19:59 UTC, lread commented
@tengstrand, ready for your review and feedback.
As always, please read the commit message before reviewing.

2023-11-23 19:53 UTC, tengstrand requested changes

2023-11-23 19:53 UTC, tengstrand commented on doc/source-code.adoc
> +* You are no longer working with a monolith and might even have separate frontend and backend releases
I suggest we change from `monolith` to `monorepo`.

2023-11-23 20:01 UTC, lread commented on doc/source-code.adoc
> +* You are no longer working with a monolith and might even have separate frontend and backend releases
Yeah, good idea, will do.

2023-11-23 20:29 UTC, lread commented on doc/source-code.adoc
> +* You are no longer working with a monolith and might even have separate frontend and backend releases
Done!

2023-11-24 04:37 UTC, merged