Review and update Validations doc
polyfy/polylith pull request #404
Opened 2023-11-24 20:15 UTC by lread

Re-organize and re-section.

Add some info on exit codes.

Add a screenshot to show an example of `ws get:messages`.

Update Warning 206 screenshot to what it should be now: Error 111.

Turf note on Warning 207 that it is only be applied to check command, it's not true anymore.

Configuration doc:
- the only reason we documented `:bricks` was to describe disabling Error 111, this is no longer a feature so we no longer need to describe `:bricks`.
- correct  description for `:necessary` and add link to Validations doc.

Edits for clarity.

2023-11-24 20:16 UTC, lread commented
@tengstrand, ready for review and feedback.
As always, please read the commit message first.

2023-11-25 05:04 UTC, tengstrand requested changes

2023-11-25 05:04 UTC, tengstrand commented on doc/configuration.adoc
> -a| `:bricks`
We need to keep this one, and add information about the `:keep-lib-versions` key, which is described in libraries.adoc. Probably a link to the library section is enough.

2023-11-25 05:04 UTC, tengstrand commented on doc/configuration.adoc
We need to add `:keep-lib-versions` here (that I missed). We could add the key to the example above also.

2023-11-25 05:04 UTC, tengstrand commented on doc/configuration.adoc
> +a| Supports turning off `Warning 207` for one or more bricks.
Good catch!

2023-11-25 16:15 UTC, lread commented on doc/configuration.adoc
> -a| `:bricks`
Aha, ok, will do.

2023-11-25 16:15 UTC, lread commented on doc/configuration.adoc
Righty-o, will do.

2023-11-25 16:16 UTC, lread commented on doc/configuration.adoc
> +a| Supports turning off `Warning 207` for one or more bricks.
tx

2023-11-25 17:06 UTC, lread commented on doc/configuration.adoc
> -a| `:bricks`
Done!

2023-11-25 17:06 UTC, lread commented on doc/configuration.adoc
Done!

2023-11-25 17:07 UTC, lread commented
@tengstrand review feedback addressed.

2023-11-25 18:58 UTC, tengstrand approved these changes

2023-11-25 18:58 UTC, merged