Review and Update Git Hook doc
polyfy/polylith pull request #409
Opened 2023-11-25 22:54 UTC by lread

Some folks find git hooks more of a nuisance than a help, so I downplayed them to make them feel like an option rather than a recommendation.

Example hook now uses the `:poly` alias for a simpler script that can be copy pasted.

Mention example hook script is OS-specific.

Add some warnings and tips.

Link to other docs.

Edits for clarity.

2023-11-25 22:54 UTC, lread commented
@tengstrand, ready for review and feedback.
As always, please read the commit message before reviewing.

2023-11-26 06:24 UTC, tengstrand requested changes

2023-11-26 06:24 UTC, tengstrand commented on doc/git-hooks.adoc
> +TIP: Consider invoking a xref:install.adoc[poly stand-alone AOT-compiled jar] for a faster `check`.
This page is about things we do when committing files, so I'm not sure if this tip should be here. If we want to keep this tip, then we should also tell the user that another option is to start a shell.

2023-11-26 17:01 UTC, lread commented on doc/git-hooks.adoc
> +TIP: Consider invoking a xref:install.adoc[poly stand-alone AOT-compiled jar] for a faster `check`.
@tengstrand, I clarified that the tip is talking about the git hook script. 
Good for you now?

2023-11-26 17:29 UTC, tengstrand approved these changes

2023-11-26 17:29 UTC, merged