Review and Update Developing Poly doc
polyfy/polylith pull request #412
Opened 2023-11-28 21:58 UTC by lread

Re-order and re-section some content for an easier to follow flow.

Add a Contributing section.
Currently my (@lread) preferences and biases, polylith core team can adapt to their point of view.

Add a few more details on cljdoc.

Give concrete example of using other workspace usage.

Edits for clarity.

2023-11-28 21:59 UTC, lread commented
@tengstrand, ready for your review and feedback!
As always please read the commit message before reviewing.

2023-11-29 03:54 UTC, tengstrand requested changes
I really like your changes. Awesome job!

2023-11-29 03:54 UTC, tengstrand commented on doc/developing-poly.adoc
> +Fake that you are using a stable production release of `poly` when you might actually be using a `SNAPSHOT` release, ' polyx`, or both.
Change ' to ` for polyx

2023-11-29 03:54 UTC, tengstrand commented on doc/developing-poly.adoc
> +poly help :fake-polya # <1>
Should be :fake-poly I guess.

2023-11-29 03:54 UTC, tengstrand commented on doc/developing-poly.adoc
>  * Use "we" when talking from the Polylith core team and "you" when directing the reader through some steps or a tutorial.
Here somewhere in this list we could tell people to use special syntax for keyboard shortcuts, found [here](https://cljdoc.org/d/polylith/clj-poly/0.2.18-SNAPSHOT/doc/shell#quit).

2023-11-29 03:54 UTC, tengstrand commented on doc/developing-poly.adoc
> +
Tell people to add a row in [next-release.txt](https://github.com/polyfy/polylith/blob/master/next-release.txt) when they create a PR. Additional info could be that this file is cleared when we make a final/stable release.

2023-11-29 16:35 UTC, lread commented on doc/developing-poly.adoc
> +Fake that you are using a stable production release of `poly` when you might actually be using a `SNAPSHOT` release, ' polyx`, or both.
tx!

2023-11-29 16:35 UTC, lread commented on doc/developing-poly.adoc
> +poly help :fake-polya # <1>
tx!

2023-11-29 16:43 UTC, lread commented on doc/developing-poly.adoc
>  * Use "we" when talking from the Polylith core team and "you" when directing the reader through some steps or a tutorial.
will do

2023-11-29 16:43 UTC, lread commented on doc/developing-poly.adoc
> +
yep, can do

2023-11-29 17:05 UTC, lread commented on doc/developing-poly.adoc
> +Fake that you are using a stable production release of `poly` when you might actually be using a `SNAPSHOT` release, ' polyx`, or both.
fixed

2023-11-29 17:05 UTC, lread commented on doc/developing-poly.adoc
> +poly help :fake-polya # <1>
vi keys get me sometimes, fixed!

2023-11-29 17:05 UTC, lread commented on doc/developing-poly.adoc
>  * Use "we" when talking from the Polylith core team and "you" when directing the reader through some steps or a tutorial.
done!

2023-11-29 17:06 UTC, lread commented on doc/developing-poly.adoc
> +
Added note

2023-11-29 17:07 UTC, lread commented
@tengstrand, thanks, all review feedback addressed!

2023-11-29 17:10 UTC, tengstrand approved these changes

2023-11-29 17:10 UTC, merged